export const tracksData = [
    { id: 74, title: "Умри если меня не любишь", artist: "DAKOOKA", file: "da_kooka_-_Bledno_belye_rozy_64441681.mp3" },
    { id: 73, title: "Невеста", artist: "Glukoza", file: "GlyukoZa_-_Nevesta_62255647.mp3" },
    { id: 72, title: "Снег идет", artist: "Glukoza", file: "GlyukoZa_-_Sneg_idet_51798391.mp3" },
    { id: 71, title: "Кухни", artist: "Бонд с кнопкой", file: "Bond_s_knopkojj_-_Kukhni_79153803.mp3" },
    { id: 70, title: "Про красивую жизнь", artist: "Банд'эрос", file: "Банд'эрос - Про красивую жизнь (hitmos.fm).mp3" },
    { id: 69, title: "Больная Любовь", artist: "Бамбинтон", file: "Bambinton_-_Bolnaya_lyubov_48210506.mp3" },
    { id: 68, title: "Маршрутка", artist: "IOWA", file: "IOWA_-_Marshrutka_48051532.mp3" },
    { id: 67, title: "Улыбайся", artist: "IOWA", file: "IOWA_-_Ulybajjsya_48057880.mp3" },
    { id: 66, title: "140", artist: "IOWA", file: "IOWA_-_140_48690789.mp3" },
    { id: 65, title: "Alive", artist: "Hugo Loud", file: "Hugo_Loud_-_Alive_79953409.mp3" },
    { id: 64, title: "Выпускной (Медлячок)", artist: "Баста", file: "Баста - Выпускной (hitmos.fm).mp3" },
    { id: 63, title: "Сансара", artist: "Баста,Диана Арбенина,Александр Ф.Скляр,Сергей Бобунец,Sunsay,Скриптонит,Ант", file: "Баста - Сансара (hitmos.fm).mp3" },
    { id: 62, title: "Привет", artist: "MATRANG,Баста", file: "MATRANG_-_Privet_64870751.mp3" },
    { id: 61, title: "Медуза", artist: "MATRANG", file: "MATRANG_-_Meduza_54769014.mp3" },
    { id: 60, title: "Малиновый рассвет", artist: "Эндшпиль", file: "JEndshpil_-_Malinovyjj_rassvet_76617209.mp3" },
    { id: 59, title: "Цепи", artist: "Скриптонит", file: "Skriptonit_-_Cepi_47828481.mp3" },
    { id: 58, title: "Москва любит", artist: "Скриптонит", file: "Skriptonit_-_Moskva_lyubit_68153451.mp3" },
    { id: 57, title: "Это любовь", artist: "Скриптонит", file: "Skriptonit_-_JEto_lyubov_47828756.mp3" },
    { id: 56, title: "Космос", artist: "Скриптонит", file: "Skriptonit_-_Kosmos_53094929.mp3" },
    { id: 55, title: "Зая", artist: "Бамбинтон", file: "Bambinton_-_Zaya_79614719.mp3" },
    { id: 54, title: "Стыцамэн", artist: "Иван Дорн", file: "Ivan_Dorn_-_Stycamjen_48213771.mp3" },
    { id: 53, title: "Бигуди", artist: "Иван Дорн", file: "Ivan_Dorn_-_Bigudi_47835763.mp3" },
    { id: 52, title: "Мама люба", artist: "SEREBRO", file: "SEREBRO_-_Mama_Lyuba_64567934.mp3" },
    { id: 51, title: "Между нам любовь", artist: "SEREBRO", file: "SEREBRO_-_Mezhdu_nami_lyubov_47828885.mp3" },
    { id: 50, title: "Я поуши в тебя влюблен", artist: "Miyagi,Andy Panda", file: "MiyaGi_Andy_Panda_-_Po_ushi_ya_v_tebya_vlyubljon_73292390.mp3" },
    { id: 49, title: "I Got Love", artist: "РЕМ ДИГГА,Miyagi,Эндшпиль", file: "Miyagi_Rem_Digga_-_I_Got_Love_47828425.mp3" },
    { id: 48, title: "Люби меня", artist: "Miyagi,Эндшпиль", file: "Miyagi_Simptom_-_Lyubi_menya_47829531.mp3" },
    { id: 47, title: "Marlboro", artist: "Miyagi", file: "Miyagi_-_Marlboro_65373356.mp3" },
    { id: 46, title: "Молодая ночь", artist: "Bacca", file: "Васса - Молодая ночь (hitmos.fm).mp3" },
    { id: 45, title: "Рукава", artist: "NEMIGA", file: "NEMIGA_-_Rukava_80157494.mp3" },
    { id: 44, title: "Белым", artist: "NEMIGA", file: "NEMIGA_-_Belym_69789265.mp3" },
    { id: 43, title: "Satisfaction", artist: "Benny Benassi", file: "Benny_Benassi_-_Satisfaction_47961034.mp3" },
    { id: 42, title: "Яд", artist: "DRIADA", file: "DRIADA_-_YAd_75207071.mp3" },
    { id: 41, title: "Los Angeles", artist: "FRIENDLY THUG 52 NGG", file: "FRIENDLY_THUG_52_NGG_-_Lost_Angeles_76929092.mp3" },
    { id: 40, title: "Still D.R.E.", artist: "Snoop Dogg,Dr.Dre", file: "Snoop_Dogg_Dr_Dre_-_Still_DRE_47964903.mp3" },
    { id: 39, title: "Ты че обиделась", artist: "Тёмный принц, Madk1d", file: "madk1d_tjomnyjj_princ_-_ty_che_obidelas_79098632.mp3" },
    { id: 38, title: "вклубе", artist: "Тёмный принц", file: "tjomnyjj_princ_-_vklube_79225575.mp3" },
    { id: 37, title: "Дежавю", artist: "Kizaru", file: "KIZARU_-_Dezhavyu_66123347.mp3" },
    { id: 36, title: "Зеркало", artist: "Kizaru", file: "kizaru_-_Zerkalo_75988545.mp3" },
    { id: 35, title: "Trap Luv", artist: "Big Baby Tape", file: "Big_Baby_Tape_-_Trap_Luv_79496151.mp3" },
    { id: 34, title: "Benzomageddon", artist: "Big Baby Tape", file: "Big_Baby_Tape_-_Benzomageddon_76967221.mp3" },
    { id: 33, title: "Turbo (Majestic)", artist: "Big Baby Tape", file: "Big_Baby_Tape_-_Turbo_Majestic_78196434.mp3" },
    { id: 32, title: "Dying 2 Live", artist: "Big Baby Tape", file: "Big_Baby_Tape_-_Dying_2_Live_76967216.mp3" },
    { id: 31, title: "Hard 2 Kill", artist: "Big Baby Tape,Jeembo", file: "Big_Baby_Tape_Jeembo_-_Hard_2_Kill_60366690.mp3" },
    { id: 30, title: "M11", artist: "Big Baby Tape, ALBLAK 52", file: "Big_Baby_Tape_ALBLAK_52_-_M11_76967233.mp3" },
    { id: 29, title: "Gimme The Loot", artist: "Big Baby Tape", file: "Big_Baby_Tape_-_Gimme_The_Loot_60366687.mp3" },
    { id: 28, title: "Ameli", artist: "Big Baby Tape,Aarne,Toxi$", file: "Big_Baby_Tape_Aarne_Toxi_-_Ameli_78055584.mp3" },
    { id: 27, title: "KARI", artist: "Big Baby Tape", file: "Big_Baby_Tape_-_KARI_80268639.mp3" },
    { id: 26, title: "Bandana", artist: "Big Baby Tape,Kizaru", file: "Big_Baby_Tape_kizaru_-_Bandana_73212029.mp3" },
    { id: 25, title: "99 problems", artist: "Big Baby Tape,Kizaru", file: "Big_Baby_Tape_kizaru_-_99_Problems_73212020.mp3" },
    { id: 24, title: "GLOCK17", artist: "BUSHIDO ZHO,Yanix", file: "BUSHIDO_ZHO_Yanix_-_GLOCK17_79459639.mp3" },
    { id: 23, title: "ВМЕСТЕ", artist: "BUSHIDO ZHO,Aarne", file: "Aarne_BUSHIDO_ZHO_-_VMESTE_76300976.mp3" },
    { id: 22, title: "SOS", artist: "BUSHIDO ZHO,Aarne", file: "Aarne_BUSHIDO_ZHO_-_SOS_78154708.mp3" },
    { id: 21, title: "vodila", artist: "BUSHIDO ZHO", file: "BUSHIDO_ZHO_-_vodila_74549801.mp3" },
    { id: 20, title: "Casino", artist: "ICEGERGERT", file: "Icegergert - Casino (hitmos.fm).mp3" },
    { id: 19, title: "Hoodtrapstar", artist: "ICEGERGERT", file: "Icegergert - Hoodtrapstar (hitmos.fm).mp3" },
    { id: 18, title: "Fake ID", artist: "ICEGERGERT,Kizaru", file: "Icegergert feat Kizaru - Fake ID (hitmos.fm).mp3" },
    { id: 17, title: "Улети", artist: "t-fest", file: "T-Fest_-_Uleti_47828757.mp3" },
    { id: 16, title: "Ламбада", artist: "t-fest", file: "T-Fest_-_Lambada_47921114.mp3" },
    { id: 15, title: "Дико, например", artist: "Pharaoh", file: "PHARAOH_-_Diko_naprimer_47921111.mp3" },
    { id: 14, title: "5 минут назад", artist: "Pharaoh", file: "PHARAOH_-_5_minut_nazad_48616847.mp3" },
    { id: 13, title: "Купер", artist: "Sqwoz bab", file: "SQWOZ_BAB_-_KUPER_80616287.mp3" },
    { id: 12, title: "Never Felt So Alone", artist: "Labrinth", file: "Labrinth_-_Never_Felt_So_Alone_80147200.mp3" },
    { id: 11, title: "Mount Everest", artist: "Labrinth", file: "Labrinth_-_Mount_Everest_80987516.mp3" },
    { id: 10, title: "Still Don't Know My Name", artist: "Labrinth", file: "Labrinth_-_Still_Dont_Know_My_Name_67181174.mp3" },
    { id: 9, title: "Formula", artist: "Labrinth", file: "Labrinth_-_Formula_67181161.mp3" },
    { id: 8, title: "Fuck Tha Police", artist: "N.W.A", file: "NWA_-_Fuck_Tha_Police_48020452.mp3" },
    { id: 7, title: "You Know How We Do It", artist: "Ice Cube", file: "Ice_Cube_-_You_Know_How_We_Do_It_48237503.mp3" },
    { id: 6, title: "It Was A Good Day", artist: "Ice Cube", file: "Ice_Cube_-_It_Was_A_Good_Day_48237505.mp3" },
    { id: 1, title: "Supreme X Vetements", artist: "FACE", file: "FACE_-_Supreme_X_Vetements_64742030.mp3" },
    { id: 2, title: "Лабиринт", artist: "FACE", file: "FACE_-_LABIRINT_66800217.mp3" },
    { id: 3, title: "PSP", artist: "FACE", file: "FACE_-_PSP_64742023.mp3" },
    { id: 4, title: "Forever Young", artist: "FACE", file: "FACE_-_Forever_Young_64629973.mp3" },
    { id: 5, title: "Tom Ford", artist: "Moreart", file: "Moreart_-_Tom_Ford_80014966.mp3" }
];
